name: Build Olive

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Clang and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build build-essential python3-pip
          sudo apt-get install -y libegl-dev libegl-mesa0 libegl1 libgl-dev libgles-dev libgles1 libgles2 libglu1-mesa libglvnd-dev libglx-dev libopengl-dev libopengl0
          
      - name: Install OpenColorIO
        run: |
          # Install required dependencies
          sudo apt-get install -y libboost-all-dev libyaml-cpp-dev
          
          # Install OpenColorIO
          git clone --branch master https://github.com/AcademySoftwareFoundation/OpenColorIO.git /tmp/OpenColorIO
          cd /tmp/OpenColorIO
          cmake -DCMAKE_INSTALL_PREFIX=/usr .
          sudo make -j$(nproc)
          sudo make install
          
      - name: Create build directory
        run: mkdir build

      - name: Build the project
        run: |
          cd build
          cmake ..
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: olive-build-artifact
          path: ./build/Olive-*.appimage
